services:
  db:
    image: postgres:13
    volumes:
      - postgresql-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
volumes:
  postgresql-data:
    driver: local
