name: Django CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      # - name: Install Poetry
      #   uses: abatilo/actions-poetry@v2.0.0

      # # Disable keyring by setting PYTHON_KEYRING_BACKEND to null
      # - name: Disable Keyring
      #   run: |
      #     echo "PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring" >> $GITHUB_ENV
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "::add-path::$(poetry config --list --local | grep 'virtualenvs.path' | cut -d' ' -f2 | sed 's|/bin/poetry||')"
      
      - name: Install Dependencies
        run: |
          poetry install

      - name: Install Dependencies
        run: |
          make install && make install-pre-commit

      - name: Lint code
        run: make lint

      # Uncomment to run tests
      # - name: Run Tests
      #   run: |
      #     python manage.py test
