name: Django CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.8.1  # Updated to the latest stable version

      - name: Disable keyring
        run: |
          export POETRY_KEYRING_BACKEND=memory

      - name: Install Dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --no-ansi

      - name: Lint code
        run: poetry run make lint

      # Uncomment to run tests
      # - name: Run Tests
      #   run: poetry run python manage.py test
